// flow-typed signature: 8ab746c9ab94730f3bcf1ddba2ce5ef9
// flow-typed version: <<STUB>>/babel-plugin-tcomb_v^0.3.25/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-tcomb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-tcomb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-tcomb/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-tcomb/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-tcomb/lib/index'>;
}
