// flow-typed signature: b1680df1c3018441d76af75a5cf1729d
// flow-typed version: <<STUB>>/babel-preset-react-optimize_v^1.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-optimize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-optimize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-react-optimize/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-react-optimize/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-react-optimize/lib/index'>;
}
