// flow-typed signature: e5faef5c71e0bd0743e9a2ab41c0bcef
// flow-typed version: <<STUB>>/eslint-config-standard_v^7.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-standard/test/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-standard/test/validate-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-standard/index' {
  declare module.exports: $Exports<'eslint-config-standard'>;
}
declare module 'eslint-config-standard/index.js' {
  declare module.exports: $Exports<'eslint-config-standard'>;
}
declare module 'eslint-config-standard/test/basic.js' {
  declare module.exports: $Exports<'eslint-config-standard/test/basic'>;
}
declare module 'eslint-config-standard/test/validate-config.js' {
  declare module.exports: $Exports<'eslint-config-standard/test/validate-config'>;
}
