// flow-typed signature: dfb4300a033f14d0f61e83b487683e80
// flow-typed version: <<STUB>>/pouchdb-browser_v^6.1.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-browser/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb-browser/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-browser/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb-browser/lib/index.es'>;
}
declare module 'pouchdb-browser/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-browser/lib/index'>;
}
