// flow-typed signature: 66c8181cb93ef596003af9544914d466
// flow-typed version: <<STUB>>/relational-pouch_v^1.4.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relational-pouch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'relational-pouch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relational-pouch/dist/pouchdb.relational-pouch' {
  declare module.exports: any;
}

declare module 'relational-pouch/dist/pouchdb.relational-pouch.min' {
  declare module.exports: any;
}

declare module 'relational-pouch/lib/collections' {
  declare module.exports: any;
}

declare module 'relational-pouch/lib/index' {
  declare module.exports: any;
}

declare module 'relational-pouch/lib/pouch-utils' {
  declare module.exports: any;
}

declare module 'relational-pouch/lib/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relational-pouch/dist/pouchdb.relational-pouch.js' {
  declare module.exports: $Exports<'relational-pouch/dist/pouchdb.relational-pouch'>;
}
declare module 'relational-pouch/dist/pouchdb.relational-pouch.min.js' {
  declare module.exports: $Exports<'relational-pouch/dist/pouchdb.relational-pouch.min'>;
}
declare module 'relational-pouch/lib/collections.js' {
  declare module.exports: $Exports<'relational-pouch/lib/collections'>;
}
declare module 'relational-pouch/lib/index.js' {
  declare module.exports: $Exports<'relational-pouch/lib/index'>;
}
declare module 'relational-pouch/lib/pouch-utils.js' {
  declare module.exports: $Exports<'relational-pouch/lib/pouch-utils'>;
}
declare module 'relational-pouch/lib/uuid.js' {
  declare module.exports: $Exports<'relational-pouch/lib/uuid'>;
}
